### ISSUE TITLE
Feature Request: Disable certain emotes

### ISSUE THREAD

**Issue by LeonBlade** [Wet-Boys/BadAssEmotes#2]
I'd like to be able to disable either the audio or specific emotes entirely, whichever is easier or more convenient. There are certain songs or emotes that I may not wish to hear, and it would be nice to disable them if they are annoying to me but I don't want to impact other users. This would be client side only.

I understand that this is very niche and you may decide it doesn't make sense to do so. I completely understand if that is your decision. I would modify it myself, but I found issue when trying to compile my own version of the plugin as it didn't seem to function properly.

**Comment by ToastedOven** [comment]
This has been added with LethalEmotesAPI 1.6.0. You can click the eyeball in the customize menu to hide emotes. If you do this, others will still be able to perform and see said emote, but you will not be able to play or see the emote
![Lethal_Company_gCsESyaDeH](https://github.com/Wet-Boys/BadAssCompany/assets/49164897/c2d47135-cf74-49fb-8296-8d0e8ebebeaf)
![Lethal_Company_sQw0xmziIe](https://github.com/Wet-Boys/BadAssCompany/assets/49164897/97012e1f-4179-457e-8468-1b9ae5075ec8)
